FROM pytorch/pytorch:1.3-cuda10.1-cudnn7-runtime

ARG DEBIAN_FRONTEND=noninteractive

# install anaconda
RUN . ~/.bashrc && \
    wget https://repo.anaconda.com/archive/Anaconda3-2019.07-Linux-x86_64.sh -O ~/Anaconda3.sh && \
    bash ~/Anaconda3.sh -b && \
    echo 'export PATH="/root/anaconda3/bin:$PATH"' >> ~/.bashrc && \
    rm ~/Anaconda3.sh
RUN . ~/.bashrc && \
    conda update --all && \

# Set normal TZ
RUN ln -sf /usr/share/zoneinfo/Europe/Moscow /etc/localtime