FROM pytorch/pytorch:1.11.0-cuda11.3-cudnn8-devel

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update && apt-get -y install \
    keyboard-configuration \
    unzip nano vim htop git wget \
    libglu1 libsm6 libxi6 \
    build-essential curl \
    libgl1-mesa-dev \
    libgl1-mesa-glx \
    libglew-dev \
    libglfw3 libosmesa6-dev \
    software-properties-common \
    net-tools \
    virtualenv \
    cmake \
    xpra \
    xserver-xorg-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install anaconda
RUN . ~/.bashrc && \
    wget https://repo.anaconda.com/archive/Anaconda3-2021.11-Linux-x86_64.sh -O ~/Anaconda3.sh && \
    bash ~/Anaconda3.sh -b && \
    echo 'export PATH="/root/anaconda3/bin:$PATH"' >> ~/.bashrc && \
    rm ~/Anaconda3.sh

COPY ./environment.yml /root/environment.yml
RUN . ~/.bashrc && \
    conda update --all && \
    conda env create -f /root/environment.yml

# Set normal TZ
RUN ln -sf /usr/share/zoneinfo/Europe/Moscow /etc/localtime