FROM pytorch/pytorch:1.11.0-cuda11.3-cudnn8-devel

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update && apt-get -y install \
    keyboard-configuration \
    unzip nano vim htop git wget \
    libglu1 libsm6 libxi6 \
    build-essential curl \
    libgl1-mesa-dev \
    libgl1-mesa-glx \
    libglew-dev \
    libglfw3 libosmesa6-dev \
    software-properties-common \
    net-tools \
    virtualenv \
    cmake \
    xpra \
    xserver-xorg-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY ./requirements.txt /root/requirements.txt
RUN . ~/.bashrc && \
    pip install --upgrade pip && \
    pip install -U -r /root/requirements.txt

# Set normal TZ
RUN ln -sf /usr/share/zoneinfo/Europe/Moscow /etc/localtime